package java.util;
import org.junit.Test;
import org.junit.Before;
import org.junit.Assert;
import informationschema.tables.InformationSchemaTableDto;
import java.util.HashMap;
import java.lang.Integer;


public class InformationsSchemaTableMapTestTests {


    @Before
    public void beforeTest(){
        Map<java.lang.Integer,informationschema.tables.InformationSchemaTableDto> map1 = new java.util.HashMap<java.lang.Integer,informationschema.tables.InformationSchemaTableDto>();
        java.lang.Integer integer2 = -29;
        informationschema.tables.InformationSchemaTableDto informationschematabledto3 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto3.setId(-29);
        informationschematabledto3.setLastModification("5");
        informationschematabledto3.setRemarks("");
        informationschematabledto3.setStorageType("STORAGE_TYPE");
        informationschematabledto3.setTableCatalog("TEST2");
        informationschematabledto3.setTableClass("org.h2.table.MetaTable");
        informationschematabledto3.setTableName("QUERY_STATISTICS");
        informationschematabledto3.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto3.setTableType("SYSTEM TABLE");
        map1.put(integer2,informationschematabledto3);
        java.lang.Integer integer4 = -28;
        informationschema.tables.InformationSchemaTableDto informationschematabledto5 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto5.setId(-28);
        informationschematabledto5.setLastModification("9223372036854775807");
        informationschematabledto5.setRemarks("");
        informationschematabledto5.setStorageType("STORAGE_TYPE");
        informationschematabledto5.setTableCatalog("TEST2");
        informationschematabledto5.setTableClass("org.h2.table.MetaTable");
        informationschematabledto5.setTableName("SESSION_STATE");
        informationschematabledto5.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto5.setTableType("SYSTEM TABLE");
        map1.put(integer4,informationschematabledto5);
        java.lang.Integer integer6 = -27;
        informationschema.tables.InformationSchemaTableDto informationschematabledto7 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto7.setId(-27);
        informationschematabledto7.setLastModification("9223372036854775807");
        informationschematabledto7.setRemarks("");
        informationschematabledto7.setStorageType("STORAGE_TYPE");
        informationschematabledto7.setTableCatalog("TEST2");
        informationschematabledto7.setTableClass("org.h2.table.MetaTable");
        informationschematabledto7.setTableName("LOCKS");
        informationschematabledto7.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto7.setTableType("SYSTEM TABLE");
        map1.put(integer6,informationschematabledto7);
        java.lang.Integer integer8 = -26;
        informationschema.tables.InformationSchemaTableDto informationschematabledto9 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto9.setId(-26);
        informationschematabledto9.setLastModification("9223372036854775807");
        informationschematabledto9.setRemarks("");
        informationschematabledto9.setStorageType("STORAGE_TYPE");
        informationschematabledto9.setTableCatalog("TEST2");
        informationschematabledto9.setTableClass("org.h2.table.MetaTable");
        informationschematabledto9.setTableName("SESSIONS");
        informationschematabledto9.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto9.setTableType("SYSTEM TABLE");
        map1.put(integer8,informationschematabledto9);
        java.lang.Integer integer10 = -25;
        informationschema.tables.InformationSchemaTableDto informationschematabledto11 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto11.setId(-25);
        informationschematabledto11.setLastModification("5");
        informationschematabledto11.setRemarks("");
        informationschematabledto11.setStorageType("STORAGE_TYPE");
        informationschematabledto11.setTableCatalog("TEST2");
        informationschematabledto11.setTableClass("org.h2.table.MetaTable");
        informationschematabledto11.setTableName("TRIGGERS");
        informationschematabledto11.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto11.setTableType("SYSTEM TABLE");
        map1.put(integer10,informationschematabledto11);
        java.lang.Integer integer12 = -24;
        informationschema.tables.InformationSchemaTableDto informationschematabledto13 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto13.setId(-24);
        informationschematabledto13.setLastModification("5");
        informationschematabledto13.setRemarks("");
        informationschematabledto13.setStorageType("STORAGE_TYPE");
        informationschematabledto13.setTableCatalog("TEST2");
        informationschematabledto13.setTableClass("org.h2.table.MetaTable");
        informationschematabledto13.setTableName("DOMAINS");
        informationschematabledto13.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto13.setTableType("SYSTEM TABLE");
        map1.put(integer12,informationschematabledto13);
        java.lang.Integer integer14 = -23;
        informationschema.tables.InformationSchemaTableDto informationschematabledto15 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto15.setId(-23);
        informationschematabledto15.setLastModification("5");
        informationschematabledto15.setRemarks("");
        informationschematabledto15.setStorageType("STORAGE_TYPE");
        informationschematabledto15.setTableCatalog("TEST2");
        informationschematabledto15.setTableClass("org.h2.table.MetaTable");
        informationschematabledto15.setTableName("CONSTANTS");
        informationschematabledto15.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto15.setTableType("SYSTEM TABLE");
        map1.put(integer14,informationschematabledto15);
        java.lang.Integer integer16 = -22;
        informationschema.tables.InformationSchemaTableDto informationschematabledto17 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto17.setId(-22);
        informationschematabledto17.setLastModification("5");
        informationschematabledto17.setRemarks("");
        informationschematabledto17.setStorageType("STORAGE_TYPE");
        informationschematabledto17.setTableCatalog("TEST2");
        informationschematabledto17.setTableClass("org.h2.table.MetaTable");
        informationschematabledto17.setTableName("FUNCTION_COLUMNS");
        informationschematabledto17.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto17.setTableType("SYSTEM TABLE");
        map1.put(integer16,informationschematabledto17);
        java.lang.Integer integer18 = -21;
        informationschema.tables.InformationSchemaTableDto informationschematabledto19 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto19.setId(-21);
        informationschematabledto19.setLastModification("5");
        informationschematabledto19.setRemarks("");
        informationschematabledto19.setStorageType("STORAGE_TYPE");
        informationschematabledto19.setTableCatalog("TEST2");
        informationschematabledto19.setTableClass("org.h2.table.MetaTable");
        informationschematabledto19.setTableName("CONSTRAINTS");
        informationschematabledto19.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto19.setTableType("SYSTEM TABLE");
        map1.put(integer18,informationschematabledto19);
        java.lang.Integer integer20 = -20;
        informationschema.tables.InformationSchemaTableDto informationschematabledto21 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto21.setId(-20);
        informationschematabledto21.setLastModification("5");
        informationschematabledto21.setRemarks("");
        informationschematabledto21.setStorageType("STORAGE_TYPE");
        informationschematabledto21.setTableCatalog("TEST2");
        informationschematabledto21.setTableClass("org.h2.table.MetaTable");
        informationschematabledto21.setTableName("CROSS_REFERENCES");
        informationschematabledto21.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto21.setTableType("SYSTEM TABLE");
        map1.put(integer20,informationschematabledto21);
        java.lang.Integer integer22 = -19;
        informationschema.tables.InformationSchemaTableDto informationschematabledto23 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto23.setId(-19);
        informationschematabledto23.setLastModification("9223372036854775807");
        informationschematabledto23.setRemarks("");
        informationschematabledto23.setStorageType("STORAGE_TYPE");
        informationschematabledto23.setTableCatalog("TEST2");
        informationschematabledto23.setTableClass("org.h2.table.MetaTable");
        informationschematabledto23.setTableName("IN_DOUBT");
        informationschematabledto23.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto23.setTableType("SYSTEM TABLE");
        map1.put(integer22,informationschematabledto23);
        java.lang.Integer integer24 = -18;
        informationschema.tables.InformationSchemaTableDto informationschematabledto25 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto25.setId(-18);
        informationschematabledto25.setLastModification("5");
        informationschematabledto25.setRemarks("");
        informationschematabledto25.setStorageType("STORAGE_TYPE");
        informationschematabledto25.setTableCatalog("TEST2");
        informationschematabledto25.setTableClass("org.h2.table.MetaTable");
        informationschematabledto25.setTableName("VIEWS");
        informationschematabledto25.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto25.setTableType("SYSTEM TABLE");
        map1.put(integer24,informationschematabledto25);
        java.lang.Integer integer26 = -17;
        informationschema.tables.InformationSchemaTableDto informationschematabledto27 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto27.setId(-17);
        informationschematabledto27.setLastModification("5");
        informationschematabledto27.setRemarks("");
        informationschematabledto27.setStorageType("STORAGE_TYPE");
        informationschematabledto27.setTableCatalog("TEST2");
        informationschematabledto27.setTableClass("org.h2.table.MetaTable");
        informationschematabledto27.setTableName("COLLATIONS");
        informationschematabledto27.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto27.setTableType("SYSTEM TABLE");
        map1.put(integer26,informationschematabledto27);
        java.lang.Integer integer28 = -16;
        informationschema.tables.InformationSchemaTableDto informationschematabledto29 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto29.setId(-16);
        informationschematabledto29.setLastModification("5");
        informationschematabledto29.setRemarks("");
        informationschematabledto29.setStorageType("STORAGE_TYPE");
        informationschematabledto29.setTableCatalog("TEST2");
        informationschematabledto29.setTableClass("org.h2.table.MetaTable");
        informationschematabledto29.setTableName("COLUMN_PRIVILEGES");
        informationschematabledto29.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto29.setTableType("SYSTEM TABLE");
        map1.put(integer28,informationschematabledto29);
        java.lang.Integer integer30 = -15;
        informationschema.tables.InformationSchemaTableDto informationschematabledto31 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto31.setId(-15);
        informationschematabledto31.setLastModification("5");
        informationschematabledto31.setRemarks("");
        informationschematabledto31.setStorageType("STORAGE_TYPE");
        informationschematabledto31.setTableCatalog("TEST2");
        informationschematabledto31.setTableClass("org.h2.table.MetaTable");
        informationschematabledto31.setTableName("TABLE_PRIVILEGES");
        informationschematabledto31.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto31.setTableType("SYSTEM TABLE");
        map1.put(integer30,informationschematabledto31);
        java.lang.Integer integer32 = -14;
        informationschema.tables.InformationSchemaTableDto informationschematabledto33 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto33.setId(-14);
        informationschematabledto33.setLastModification("5");
        informationschematabledto33.setRemarks("");
        informationschematabledto33.setStorageType("STORAGE_TYPE");
        informationschematabledto33.setTableCatalog("TEST2");
        informationschematabledto33.setTableClass("org.h2.table.MetaTable");
        informationschematabledto33.setTableName("SCHEMATA");
        informationschematabledto33.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto33.setTableType("SYSTEM TABLE");
        map1.put(integer32,informationschematabledto33);
        java.lang.Integer integer34 = -13;
        informationschema.tables.InformationSchemaTableDto informationschematabledto35 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto35.setId(-13);
        informationschematabledto35.setLastModification("5");
        informationschematabledto35.setRemarks("");
        informationschematabledto35.setStorageType("STORAGE_TYPE");
        informationschematabledto35.setTableCatalog("TEST2");
        informationschematabledto35.setTableClass("org.h2.table.MetaTable");
        informationschematabledto35.setTableName("FUNCTION_ALIASES");
        informationschematabledto35.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto35.setTableType("SYSTEM TABLE");
        map1.put(integer34,informationschematabledto35);
        java.lang.Integer integer36 = -12;
        informationschema.tables.InformationSchemaTableDto informationschematabledto37 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto37.setId(-12);
        informationschematabledto37.setLastModification("5");
        informationschematabledto37.setRemarks("");
        informationschematabledto37.setStorageType("STORAGE_TYPE");
        informationschematabledto37.setTableCatalog("TEST2");
        informationschematabledto37.setTableClass("org.h2.table.MetaTable");
        informationschematabledto37.setTableName("RIGHTS");
        informationschematabledto37.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto37.setTableType("SYSTEM TABLE");
        map1.put(integer36,informationschematabledto37);
        java.lang.Integer integer38 = -11;
        informationschema.tables.InformationSchemaTableDto informationschematabledto39 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto39.setId(-11);
        informationschematabledto39.setLastModification("5");
        informationschematabledto39.setRemarks("");
        informationschematabledto39.setStorageType("STORAGE_TYPE");
        informationschematabledto39.setTableCatalog("TEST2");
        informationschematabledto39.setTableClass("org.h2.table.MetaTable");
        informationschematabledto39.setTableName("ROLES");
        informationschematabledto39.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto39.setTableType("SYSTEM TABLE");
        map1.put(integer38,informationschematabledto39);
        java.lang.Integer integer40 = -10;
        informationschema.tables.InformationSchemaTableDto informationschematabledto41 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto41.setId(-10);
        informationschematabledto41.setLastModification("5");
        informationschematabledto41.setRemarks("");
        informationschematabledto41.setStorageType("STORAGE_TYPE");
        informationschematabledto41.setTableCatalog("TEST2");
        informationschematabledto41.setTableClass("org.h2.table.MetaTable");
        informationschematabledto41.setTableName("USERS");
        informationschematabledto41.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto41.setTableType("SYSTEM TABLE");
        map1.put(integer40,informationschematabledto41);
        java.lang.Integer integer42 = -9;
        informationschema.tables.InformationSchemaTableDto informationschematabledto43 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto43.setId(-9);
        informationschematabledto43.setLastModification("5");
        informationschematabledto43.setRemarks("");
        informationschematabledto43.setStorageType("STORAGE_TYPE");
        informationschematabledto43.setTableCatalog("TEST2");
        informationschematabledto43.setTableClass("org.h2.table.MetaTable");
        informationschematabledto43.setTableName("SEQUENCES");
        informationschematabledto43.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto43.setTableType("SYSTEM TABLE");
        map1.put(integer42,informationschematabledto43);
        java.lang.Integer integer44 = -8;
        informationschema.tables.InformationSchemaTableDto informationschematabledto45 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto45.setId(-8);
        informationschematabledto45.setLastModification("5");
        informationschematabledto45.setRemarks("");
        informationschematabledto45.setStorageType("STORAGE_TYPE");
        informationschematabledto45.setTableCatalog("TEST2");
        informationschematabledto45.setTableClass("org.h2.table.MetaTable");
        informationschematabledto45.setTableName("HELP");
        informationschematabledto45.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto45.setTableType("SYSTEM TABLE");
        map1.put(integer44,informationschematabledto45);
        java.lang.Integer integer46 = -7;
        informationschema.tables.InformationSchemaTableDto informationschematabledto47 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto47.setId(-7);
        informationschematabledto47.setLastModification("9223372036854775807");
        informationschematabledto47.setRemarks("");
        informationschematabledto47.setStorageType("STORAGE_TYPE");
        informationschematabledto47.setTableCatalog("TEST2");
        informationschematabledto47.setTableClass("org.h2.table.MetaTable");
        informationschematabledto47.setTableName("SETTINGS");
        informationschematabledto47.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto47.setTableType("SYSTEM TABLE");
        map1.put(integer46,informationschematabledto47);
        java.lang.Integer integer48 = -6;
        informationschema.tables.InformationSchemaTableDto informationschematabledto49 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto49.setId(-6);
        informationschematabledto49.setLastModification("5");
        informationschematabledto49.setRemarks("");
        informationschematabledto49.setStorageType("STORAGE_TYPE");
        informationschematabledto49.setTableCatalog("TEST2");
        informationschematabledto49.setTableClass("org.h2.table.MetaTable");
        informationschematabledto49.setTableName("CATALOGS");
        informationschematabledto49.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto49.setTableType("SYSTEM TABLE");
        map1.put(integer48,informationschematabledto49);
        java.lang.Integer integer50 = -5;
        informationschema.tables.InformationSchemaTableDto informationschematabledto51 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto51.setId(-5);
        informationschematabledto51.setLastModification("5");
        informationschematabledto51.setRemarks("");
        informationschematabledto51.setStorageType("STORAGE_TYPE");
        informationschematabledto51.setTableCatalog("TEST2");
        informationschematabledto51.setTableClass("org.h2.table.MetaTable");
        informationschematabledto51.setTableName("TYPE_INFO");
        informationschematabledto51.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto51.setTableType("SYSTEM TABLE");
        map1.put(integer50,informationschematabledto51);
        java.lang.Integer integer52 = -4;
        informationschema.tables.InformationSchemaTableDto informationschematabledto53 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto53.setId(-4);
        informationschematabledto53.setLastModification("5");
        informationschematabledto53.setRemarks("");
        informationschematabledto53.setStorageType("STORAGE_TYPE");
        informationschematabledto53.setTableCatalog("TEST2");
        informationschematabledto53.setTableClass("org.h2.table.MetaTable");
        informationschematabledto53.setTableName("TABLE_TYPES");
        informationschematabledto53.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto53.setTableType("SYSTEM TABLE");
        map1.put(integer52,informationschematabledto53);
        java.lang.Integer integer54 = -3;
        informationschema.tables.InformationSchemaTableDto informationschematabledto55 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto55.setId(-3);
        informationschematabledto55.setLastModification("5");
        informationschematabledto55.setRemarks("");
        informationschematabledto55.setStorageType("STORAGE_TYPE");
        informationschematabledto55.setTableCatalog("TEST2");
        informationschematabledto55.setTableClass("org.h2.table.MetaTable");
        informationschematabledto55.setTableName("INDEXES");
        informationschematabledto55.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto55.setTableType("SYSTEM TABLE");
        map1.put(integer54,informationschematabledto55);
        java.lang.Integer integer56 = -2;
        informationschema.tables.InformationSchemaTableDto informationschematabledto57 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto57.setId(-2);
        informationschematabledto57.setLastModification("5");
        informationschematabledto57.setRemarks("");
        informationschematabledto57.setStorageType("STORAGE_TYPE");
        informationschematabledto57.setTableCatalog("TEST2");
        informationschematabledto57.setTableClass("org.h2.table.MetaTable");
        informationschematabledto57.setTableName("COLUMNS");
        informationschematabledto57.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto57.setTableType("SYSTEM TABLE");
        map1.put(integer56,informationschematabledto57);
        java.lang.Integer integer58 = -1;
        informationschema.tables.InformationSchemaTableDto informationschematabledto59 = new informationschema.tables.InformationSchemaTableDto();
        informationschematabledto59.setId(-1);
        informationschematabledto59.setLastModification("5");
        informationschematabledto59.setRemarks("");
        informationschematabledto59.setStorageType("STORAGE_TYPE");
        informationschematabledto59.setTableCatalog("TEST2");
        informationschematabledto59.setTableClass("org.h2.table.MetaTable");
        informationschematabledto59.setTableName("TABLES");
        informationschematabledto59.setTableSchema("INFORMATION_SCHEMA");
        informationschematabledto59.setTableType("SYSTEM TABLE");
        map1.put(integer58,informationschematabledto59);
    }

}
